server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: asset-service
          uri: lb://asset-service
          predicates:
            - Path=/assets/**
        - id: maintenance-service
          uri: lb://maintenance-service
          predicates:
            - Path=/maintenance/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: monitoring-service
          uri: lb://monitoring-service
          predicates:
            - Path=/monitoring/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"